### PR TITLE
Complete homepage

### LINKED ISSUE #10: Initial steps for merging upstream
Hi!

So according to the recent poll, looks like most people favour ScoopSearch. Which is awesome!

The user-facing website looks like this: (`{base}` is `scoopsearch.github.io` as of now)

- `{base}/#/apps`: Takes user to application search page.
- `{base}/#/buckets`: Takes user to list of all public buckets.
- `{base}`: This would be homepage (it currently redirects to `{base}/#/apps`).

So the first step would be to create a brand new homepage (the current one has some slightly out-of-date info, but we can start from scratch). The broad overview can be taken from the current Readme, selecting the most relevant parts - i.e. what Scoop is, why you need it, and a quick-start. Links for documentation (the Scoop GitHub Readme and Wiki) can be added at the bottom.

Let me know what you think!

### PR DESCRIPTION
**Pull request by rashil2000**
Closes #10

### CODE REVIEW

**Comment by rashil2000** [comment]
@gpailler could you deploy this to https://github.com/ScoopSearch/scoopsearch-dev.github.io so that it can be previewed by anyone?

**Comment by gpailler** [comment]
Hey @rashil2000 . You branch is merged and the result is available on https://scoopsearch.github.io/scoopsearch-dev.github.io/
(I just had to fix a couple of styling/linting issues).
You can also commit directly on the develop branch if you prefer so the changes are immediately available.

About the homepage itself, I would propose to have the `Discovering Packages` section before the package creation example (or even just after the vscode example). As a first time user, I think that you want to see an example then the list of the available packages first. Then, you want to learn more details about scoop (where are the files, how to create a package...)

**Comment by rashil2000** [comment]
Hey, I have made the requested change - https://github.com/ScoopSearch/ScoopSearch.WebSearchEngine/commit/305811af7272bfe6d8e301fd86a1cee80c2a2e1c. Let me know how it is :)

**Comment by gpailler** [comment]
The ordering looks better 👍 . There is probably some room for layout improvement. I think it's time to call our UX/UI expert !
Let's continue the discussion on #11

**Pull request merged**
